dist: freebsd
group: dev

before_install:
  - ls /usr/local/bin
  - ls /bin
  - whereis jdk_switcher
  - whereis jdk_switcher.sh
  - cat ~/.bashrc
  - cat ~/.cshrc
  - echo $JAVA_HOME
  - echo $JDK_SWITCHER_DEFAULT
  - echo $OPENJDK_VENDOR
  - echo $OPENJDK12_VERSION
  - ls -ls ~/.bash_profile.d/
  - cat ~/.bash_profile.d/travis-java.bash
  - ls -la /opt/jdk_switcher
  - cat /opt/jdk_switcher/jdk_switcher.sh
